<!DOCTYPE html>
<html lang="en">
    <head>
        @include('home.partials.head')
    </head>
    <body id="page-top">

        @include('home.partials.menu')
        
       
        <!-- About-->
        {{-- <section class="about-section text-center" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8">
                        <h2 class="text-white mb-4">Built with Bootstrap 5</h2>
                        <p class="text-white-50">
                            Grayscale is a free Bootstrap theme created by Start Bootstrap. It can be yours right now, simply download the template on
                            <a href="https://startbootstrap.com/theme/grayscale/">the preview page.</a>
                            The theme is open source, and you can use it for any purpose, personal or commercial.
                        </p>
                    </div>
                </div>
                <img class="img-fluid" src="{{ asset('home/images/ipad.png') }}" alt="..." />
            </div>
        </section> --}}
        <!-- Projects-->
        <section class="projects-section" id="projects">
            <div class="container px-4 px-lg-5">
                <!-- Featured Project Row-->
                <div class="row align-items-center">
                    <div class="col-lg-12">
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;text-indent:36.0pt;'><strong><span style='font-size:27px;line-height:107%;font-family:"Times New Roman",serif;'>GIỚI THIỆU CÔNG TY</span></strong></p>

                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">1. GIỚI THIỆU DỊCH VỤ</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">ALI LOGISTIC&nbsp;</span><span style="color:black;">&nbsp;l&agrave; đơn vị trung gian cung cấp c&aacute;c dịch vụ đặt h&agrave;ng, vận chuyển h&agrave;ng th&ocirc;ng qua c&aacute;c website thương mại điện tử Trung Quốc (1688.com, Taobao.com, Tmall.com, Alibaba.com, Wechat &hellip; ) hoặc trực tiếp từ c&aacute;c nh&agrave; m&aacute;y/c&ocirc;ng xưởng về Việt Nam.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">2. C&Aacute;C MẶT H&Agrave;NG KH&Ocirc;NG VẬN CHUYỂN</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Vũ kh&iacute;, đạn dược, vật liệu nổ, trang thiết bị kỹ thuật qu&acirc;n sự (s&uacute;ng, đạn, đao,...).</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- C&aacute;c loại chất ma t&uacute;y, g&acirc;y k&iacute;ch th&iacute;ch thần kinh.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Vật hoặc chất dễ nổ, dễ ch&aacute;y v&agrave; c&aacute;c chất g&acirc;y nguy hiểm hoặc l&agrave;m mất vệ sinh, g&acirc;y &ocirc; nhiễm m&ocirc;i trường.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Động vật, thực vật sống.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Thực phẩm, mỹ phẩm, đồ chơi trẻ em,... kh&ocirc;ng x&aacute;c nhận nguồn gốc, c&oacute; chất g&acirc;y độc hại ảnh hưởng đến người sử dụng.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- C&aacute;c loại xuất bản phẩm cấm phổ biến v&agrave; lưu h&agrave;nh tại Việt Nam:</span></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Tem bưu ch&iacute;nh thuộc diện cấm kinh doanh, trao đổi, trưng b&agrave;y, tuy&ecirc;n truyền theo quy định của Luật Bưu ch&iacute;nh.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Thiết bị v&ocirc; tuyến điện, thiết bị ứng dụng s&oacute;ng v&ocirc; tuyến điện kh&ocirc;ng ph&ugrave; hợp với c&aacute;c quy hoạch tần số v&ocirc; tuyến điện v&agrave; quy chuẩn kỹ thuật c&oacute; li&ecirc;n quan theo quy định của Luật Tần số v&ocirc; tuyến điện.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- C&aacute;c loại văn h&oacute;a phẩm thuộc diện cấm phổ biến v&agrave; lưu h&agrave;nh hoặc c&oacute; quyết định đ&igrave;nh chỉ phổ biến v&agrave; lưu h&agrave;nh tại Việt Nam.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Bao gồm c&aacute;c loại h&agrave;ng h&oacute;a trong danh mục cấm vận chuyển, kinh doanh theo quy định Ph&aacute;p luật Việt Nam</span><span style="color:black;">&nbsp;: thuốc l&aacute; điện tử, x&igrave; g&agrave;, v&agrave; c&aacute;c dạng thuốc l&aacute; th&agrave;nh phẩm kh&aacute;c,&hellip;.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">3. C&Aacute;CH THỨC MUA H&Agrave;NG V&Agrave; THANH TO&Aacute;N&nbsp;</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><em><span style="color:black;">- Tạo t&agrave;i khoản mua h&agrave;ng:</span></em></strong></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Trước khi mua h&agrave;ng, Qu&yacute; kh&aacute;ch cần phải đăng k&yacute; t&agrave;i khoản tr&ecirc;n Website của&nbsp;</span><span style="color:black;">Alilogi&nbsp;</span><span style="color:black;">&nbsp;v&agrave; cung cấp c&aacute;c th&ocirc;ng tin c&aacute; nh&acirc;n ch&iacute;nh x&aacute;c theo biểu mẫu đ&atilde; quy định v&agrave; x&aacute;c thực t&agrave;i khoản qua&nbsp;</span><span style="color:black;">email c&aacute; nh&acirc;n.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;cam kết c&oacute; tr&aacute;ch nhiệm bảo vệ những th&ocirc;ng tin người d&ugrave;ng, kh&ocirc;ng được sử dụng cho mục đ&iacute;ch n&agrave;o kh&aacute;c ngo&agrave;i hệ thống m&agrave; Qu&yacute; kh&aacute;ch đ&atilde; đăng k&yacute;.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Qu&yacute; kh&aacute;ch c&oacute; tr&aacute;ch nhiệm bảo mật đối với t&agrave;i khoản của m&igrave;nh,&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;kh&ocirc;ng chịu tr&aacute;ch nhiệm về việc sử dụng t&agrave;i khoản m&agrave; c&aacute;c lỗi ph&aacute;t sinh từ ph&iacute;a người sử dụng.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><em><span style="color:black;">- Phương thức mua h&agrave;ng:</span></em></strong></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Để mua h&agrave;ng tr&ecirc;n c&aacute;c website thương mại (&quot;TMĐT&quot;) Taobao, 1688, Tmall, qu&yacute; kh&aacute;ch thực hiện việc đặt h&agrave;ng trực tiếp tr&ecirc;n Website&nbsp;</span><span style="color:black;">Alilogi.vn</span><span style="color:black;">&nbsp;th&ocirc;ng qua c&ocirc;ng cụ đặt h&agrave;ng t&iacute;ch hợp (add-on). Al</span><span style="color:black;">ilogi</span><span style="color:black;">&nbsp;sẽ ghi nhận v&agrave; thực hiện việc thanh to&aacute;n v&agrave; vận chuyển h&agrave;ng h&oacute;a về cho Qu&yacute; kh&aacute;ch. Với những đối t&aacute;c kh&ocirc;ng t&iacute;ch hợp c&ocirc;ng cụ đặt h&agrave;ng để tạo đơn h&agrave;ng được (Wechat, alibaba.com, jd.com, paipai.com, Website b&aacute;n h&agrave;ng của xưởng&hellip;), Qu&yacute; kh&aacute;ch vui l&ograve;ng tạo đơn h&agrave;ng theo sự hướng dẫn của nh&acirc;n vi&ecirc;n CSKH.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;cam kết mua h&agrave;ng trong v&ograve;ng 24h kể từ khi kh&aacute;ch h&agrave;ng đẩy thanh to&aacute;n đặt cọc tr&ecirc;n hệ thống v&iacute;. Ngoại trừ c&aacute;c trường hợp đặc biệt Sale; ng&agrave;y nghỉ lễ của Việt Nam v&agrave; Trung Quốc; ng&agrave;y Chủ nhật; Biến động về ch&iacute;nh trị, thị trường&hellip;</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><em><span style="color:black;">- Phương thức thanh to&aacute;n:</span></em></strong></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Kh&aacute;ch h&agrave;ng vui l&ograve;ng nạp tiền v&agrave;o hệ thống v&iacute; điện tử của&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;để thực hiện c&aacute;c giao dịch thanh to&aacute;n mua h&agrave;ng, vận chuyển. Tỷ gi&aacute; giữa Nh&acirc;n d&acirc;n tệ (NDT) v&agrave; Việt Nam đồng của&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;l&agrave; tỷ gi&aacute; tự do theo thị trường v&agrave; t&iacute;nh to&aacute;n ở mức hợp l&yacute; nhất cho kh&aacute;ch h&agrave;ng. Nếu c&oacute; sự thay đổi về tỷ gi&aacute;, ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o trước tr&ecirc;n website v&agrave; fanpage.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Kh&aacute;ch h&agrave;ng thanh to&aacute;n tiền cọc từ&nbsp;</span><span style="color:black;">70%</span><span style="color:black;">&nbsp;tổng số tiền đơn h&agrave;ng chưa bao gồm ph&iacute; vận chuyển cho&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;tr&ecirc;n hệ thống v&iacute; điện tử.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Tr&ecirc;n đơn h&agrave;ng tại thời điểm kh&aacute;ch h&agrave;ng đặt cọc c&oacute; thể sẽ chưa c&oacute; ph&iacute; vận chuyển nội địa Trung Quốc (chuyển h&agrave;ng từ NCC về đến kho&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;tại Trung Quốc).&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;sẽ thanh to&aacute;n tiền h&agrave;ng v&agrave; ph&iacute; vận chuyển nội địa với nh&agrave; cung cấp (nếu c&oacute; ph&aacute;t sinh tại thời điểm đặt h&agrave;ng với nh&agrave; cung cấp) v&agrave; tự động cập nhật ph&iacute; vận chuyển nội địa v&agrave;o đơn h&agrave;ng m&agrave; kh&ocirc;ng cần b&aacute;o trước cho kh&aacute;ch h&agrave;ng, trừ trường hợp ph&iacute; vận chuyển vượt qu&aacute; mức khung gi&aacute; th&ocirc;ng thường (từ 8 - 12 tệ/kg đầu ti&ecirc;n v&agrave; 2-5 tệ/kg tiếp theo) th&igrave;&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;sẽ trao đổi với kh&aacute;ch h&agrave;ng để x&aacute;c nhận xem kh&aacute;ch h&agrave;ng c&oacute; đặt mua tiếp hay kh&ocirc;ng. Nếu kh&aacute;ch h&agrave;ng muốn biết cước vận chuyển nội địa Trung Quốc trước khi HVT đặt mua h&agrave;ng với nh&agrave; cung cấp Trung Quốc th&igrave; kh&aacute;ch h&agrave;ng cần trao đổi trước với nh&acirc;n vi&ecirc;n CSKH.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Khi h&agrave;ng h&oacute;a về đến kho Việt Nam, Qu&yacute; kh&aacute;ch vui l&ograve;ng thanh to&aacute;n số tiền c&ograve;n lại của đơn h&agrave;ng cho&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;tr&ecirc;n hệ thống v&iacute; hoặc tiền mặt trước khi nhận h&agrave;ng.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><em><span style="color:black;">- Kết th&uacute;c đơn h&agrave;ng:</span></em></strong></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Sau 24h kể từ thời điểm giao h&agrave;ng m&agrave; kh&ocirc;ng c&oacute; khiếu nại, hệ thống sẽ tự động kết th&uacute;c đơn h&agrave;ng. Qu&yacute; kh&aacute;ch lưu &yacute;,&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;sẽ kh&ocirc;ng tiếp nhận khiếu nại sau khoảng thời gian n&agrave;y.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">4</span></strong><strong><span style="color:black;">. CH&Iacute;NH S&Aacute;CH GIAO H&Agrave;NG V&Agrave; LƯU KHO H&Agrave;NG H&Oacute;A</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Sau khi h&agrave;ng nhập kho, Qu&yacute; kh&aacute;ch vui l&ograve;ng thanh to&aacute;n to&agrave;n bộ gi&aacute; trị c&ograve;n lại của đơn h&agrave;ng v&agrave; tạo y&ecirc;u cầu giao h&agrave;ng trong v&ograve;ng 5 ng&agrave;y, trong thời gian n&agrave;y&nbsp;</span><span style="color:black;">Alilogi&nbsp;</span><span style="color:black;">&nbsp;ph&iacute; lưu kho v&agrave; c&oacute; tr&aacute;ch nhiệm đảm bảo rủi ro h&agrave;ng h&oacute;a. Thời gian giao h&agrave;ng tại kho nằm trong khung giờ h&agrave;nh ch&iacute;nh s&aacute;ng: 8h00-12h00 v&agrave; chiều từ 13h30 - 18h00 h&agrave;ng ng&agrave;y từ T2 đến s&aacute;ng T7, trừ c&aacute;c ng&agrave;y Lễ, Tết.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:18.0pt;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Thời điểm t&iacute;nh ph&iacute; lưu kho: sau 5 ng&agrave;y kể từ khi h&agrave;ng h&oacute;a (theo bill) được nhập kho v&agrave; hiển thị trạng th&aacute;i &ldquo;<em>h&agrave;ng đ&atilde; về HN</em>&rdquo; hoặc &ldquo;<em>h&agrave;ng đ&atilde; về HCM</em>&rdquo; m&agrave; kh&aacute;ch h&agrave;ng kh&ocirc;ng tiếp nhận b&agrave;n giao h&agrave;ng.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:18.0pt;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Mức ph&iacute; lưu kho: 2000đ/kg/ng&agrave;y t&iacute;nh tr&ecirc;n mỗi bill h&agrave;ng v&agrave; được cộng thẳng trực tiếp v&agrave;o tổng gi&aacute; trị đơn h&agrave;ng.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:18.0pt;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Đối với h&agrave;ng h&oacute;a lưu kho qu&aacute; 15 ng&agrave;y, nếu kh&aacute;ch h&agrave;ng kh&ocirc;ng ho&agrave;n th&agrave;nh nghĩa vụ thanh to&aacute;n v&agrave; tạo y&ecirc;u cầu giao h&agrave;ng,&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;c&oacute; quyền thanh l&yacute; số h&agrave;ng h&oacute;a tồn để b&ugrave; v&agrave;o gi&aacute; trị đơn h&agrave;ng c&ograve;n lại v&agrave; sẽ kh&ocirc;ng c&oacute; tr&aacute;ch nhiệm phải bồi ho&agrave;n h&agrave;ng h&oacute;a hoặc ho&agrave;n trả tiền đặt cọc trước đ&oacute;.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:18.0pt;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Trường hợp Qu&yacute; kh&aacute;ch đ&atilde; thanh to&aacute;n đầy đủ 100% gi&aacute; trị đơn h&agrave;ng nhưng muốn k&yacute; gửi h&agrave;ng h&oacute;a tại kho của&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;th&igrave; thời gian tối đa lưu kho cũng kh&ocirc;ng qu&aacute; 30 ng&agrave;y. Trong thời gian lưu kho c&oacute; t&iacute;nh ph&iacute;, mọi vấn đề rủi ro của đơn h&agrave;ng nếu c&oacute; ph&aacute;t sinh&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">5</span></strong><strong><span style="color:black;">. QUY ĐỊNH VỀ XỬ L&Yacute; KHIẾU NẠI</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">5.</span></strong><strong><span style="color:black;">1 Thời gian thực hiện, tiếp nhận v&agrave; xử l&yacute; khiếu nại</span></strong></p>
                        <ul class="decimal_type" style="list-style-type: disc;margin-left:4.199999999999999px;">
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Thời gian kh&aacute;ch h&agrave;ng gửi khiếu nại: Trong v&ograve;ng 48h kể từ khi nhận h&agrave;ng.&nbsp;</span></li>
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>C&aacute;ch thức gửi th&ocirc;ng tin : Qu&yacute; kh&aacute;ch gửi th&ocirc;ng tin khiếu nại của đơn h&agrave;ng cho nh&acirc;n vi&ecirc;n phụ tr&aacute;ch ri&ecirc;ng của m&igrave;nh</span></li>
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Qu&yacute; kh&aacute;ch cung cấp th&ocirc;ng tin ch&iacute;nh x&aacute;c l&agrave; cơ sở để ch&uacute;ng t&ocirc;i hỗ trợ Qu&yacute; kh&aacute;ch khiếu nại với shop đạt hiệu quả cao.&nbsp;</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>H&igrave;nh thức li&ecirc;n lạc:</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;Người phụ tr&aacute;ch trực tiếp sẽ th&ocirc;ng b&aacute;o t&igrave;nh h&igrave;nh xử l&yacute; khiếu nại tới qu&yacute; kh&aacute;ch</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Thời gian tiếp nhận v&agrave; xử l&yacute; khiếu nại:</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;Khiếu nại của Qu&yacute; kh&aacute;ch sẽ được phản hồi trong v&ograve;ng 1 ng&agrave;y nếu khiếu nại của Qu&yacute; kh&aacute;ch li&ecirc;n quan tới c&aacute;c bộ phận nghiệp vụ của C&ocirc;ng ty.&nbsp;</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Nếu khiếu nại của Qu&yacute; kh&aacute;ch li&ecirc;n quan tới nh&agrave; cung cấp</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>, phản hồi của ch&uacute;ng t&ocirc;i sẽ gửi tới qu&yacute; kh&aacute;ch trong v&ograve;ng 3-4 ng&agrave;y phụ thuộc v&agrave;o sự &nbsp; hợp t&aacute;c của nh&agrave; cung cấp.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:35.45pt;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;text-indent:-35.45pt;background:white;'><strong><span style="color:black;">5.2</span></strong><strong><span style="color:black;">&nbsp;Ch&iacute;nh s&aacute;ch bồi thường</span></strong></p>
                        <ul style="list-style-type: disc;margin-left:25.450000000000003px;">
                            <li><strong><u><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>ĐỐI VỚI H&Agrave;NG VẬN CHUYỂN</span></u></strong></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với trường hợp h&agrave;ng h&oacute;a bị thất lạc, hư hỏng</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>: Do ch&uacute;ng t&ocirc;i kh&ocirc;ng trực tiếp giao dịch với nh&agrave; cung cấp của Qu&yacute; kh&aacute;ch, cũng kh&ocirc;ng cung cấp dịch vụ kiểm h&agrave;ng cho c&aacute;c đơn h&agrave;ng vận chuyển, khi h&agrave;ng h&oacute;a của Qu&yacute; kh&aacute;ch được nh&agrave; cung cấp vận chuyển đến ch&uacute;ng t&ocirc;i chỉ nhận h&agrave;ng theo số kiện Qu&yacute; kh&aacute;ch đ&atilde; k&ecirc; khai. V&igrave; vậy ch&uacute;ng tối sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm với t&igrave;nh trạng hư hỏng của h&agrave;ng h&oacute;a. &nbsp;C&ocirc;ng ty sẽ đền b&ugrave; 100% gi&aacute; trị h&agrave;ng tối đa kh&ocirc;ng qu&aacute; 2.000.000đ/ 1 m&atilde; vận đơn hoặc đền b&ugrave; gấp 5 -10 lần gi&aacute; trị vận tải trong trường hợp h&agrave;ng h&oacute;a bị thất lạc.</span></li>
                        </ul>
                        <ul class="decimal_type" style="list-style-type: undefined;margin-left:1cmundefined;">
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với trường hợp h&agrave;ng h&oacute;a bị cơ quan chức năng thu giữ</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>: C&ocirc;ng ty sẽ l&agrave;m việc lại với qu&yacute; kh&aacute;ch để &nbsp;đưa ra phương &aacute;n đền b&ugrave; ph&ugrave; hợp , giảm thiểu tối đa tổn thất của hai b&ecirc;n.&nbsp;</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với đơn h&agrave;ng mua bảo hiểm</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>: Nếu qu&yacute; kh&aacute;ch sử dụng dịch vụ bảo hiểm h&agrave;ng h&oacute;a ( kh&ocirc;ng nhận bảo hiểm đối với những trường hợp h&agrave;ng h&oacute;a dễ vỡ ) , trường hợp xảy ra mất h&agrave;ng h&oacute;a c&ocirc;ng ty sẽ bồi thường 100% gi&aacute; trị h&agrave;ng h&oacute;a bị mất, ph&iacute; bảo hiểm h&agrave;ng h&oacute;a l&agrave; 3% tr&ecirc;n tổng gi&aacute; trị đơn h&agrave;ng. Ch&uacute;ng t&ocirc;i khuyến kh&iacute;ch kh&aacute;ch h&agrave;ng sử dụng th&ecirc;m dịch vụ n&agrave;y để giảm thiểu rủi ro tối đa.&nbsp;</span></li>
                            <li><strong><u><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>ĐỐI VỚI H&Agrave;NG ORDER</span></u></strong></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trường hợp h&agrave;ng h&oacute;a bị thất lạc trong qu&aacute; tr&igrave;nh vận chuyển</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;do c&aacute;c nguy&ecirc;n nh&acirc;n chủ quan hoặc kh&aacute;ch quan, C&ocirc;ng ty sẽ bồi thường 100% gi&aacute; trị h&agrave;ng h&oacute;a v&agrave; c&aacute;c ph&iacute; dịch vụ li&ecirc;n quan</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trường hợp C&ocirc;ng ty Alilogi thực &nbsp;hiện kh&ocirc;ng đ&uacute;ng cam kết dịch vụ mua h&agrave;ng</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;, ch&uacute;ng t&ocirc;i sẽ bồi thường 100% gi&aacute; trị tiền h&agrave;ng v&agrave; ph&iacute; mua h&agrave;ng đối với c&aacute;c sản phẩm thiếu</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với những trường hợp h&agrave;ng h&oacute;a dễ vỡ</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;m&agrave; ch&uacute;ng t&ocirc;i đ&atilde; cảnh b&aacute;o qu&yacute; kh&aacute;ch, nếu h&agrave;ng h&oacute;a của qu&yacute; kh&aacute;ch vẫn bị hỏng h&oacute;c v&igrave; những l&yacute; do kh&ocirc;ng kiểm so&aacute;t được, qu&yacute; kh&aacute;ch vui l&ograve;ng chịu mọi tổn thất.</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với những đơn đặt h&agrave;ng mua ngo&agrave;i c&aacute;c trang 1688, taobao, tmall:</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;Qu&yacute; kh&aacute;ch vui l&ograve;ng đặt cọc 100% gi&aacute; trị đơn h&agrave;ng. Alilogi kh&ocirc;ng chịu tr&aacute;ch nhiệm trước những rủi ro khi thanh to&aacute;n v&agrave; kh&ocirc;ng đảm bảo đền b&ugrave; khiếu nại của đơn h&agrave;ng.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:7.1pt;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;text-indent:-7.1pt;background:white;'><strong><span style="color:black;">5.3</span></strong><strong><span style="color:black;">. Ch&iacute;nh s&aacute;ch hỗ trợ đối với c&aacute;c khiếu nại kh&ocirc;ng nằm trong phạm vi cam kết dịch vụ</span></strong></p>
                        <ul style="list-style-type: disc;margin-left:1cmundefined;">
                            <li><strong><span style="line-height:107%;font-size:19px;">&nbsp; Đối với c&aacute;c khiếu nại li&ecirc;n quan đến NCC khi NCC vi phạm điều khoản giao dịch h&agrave;ng h&oacute;a</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>&nbsp;( điều khoản giao dịch tr&ecirc;n c&aacute;c website b&aacute;n h&agrave;ng), ch&uacute;ng t&ocirc;i sẽ trực tiếp xử l&yacute; &nbsp;hoặc hỗ trợ qu&yacute; kh&aacute;ch xử l&yacute;. Alilogi y&ecirc;u cầu qu&yacute; kh&aacute;ch hợp t&aacute;c c&ugrave;ng ch&uacute;ng t&ocirc;i trong suốt thời gian xử l&yacute; khiếu nại.</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trong trường hợp q&uacute;y kh&aacute;ch đ&atilde; c&oacute; thỏa thuận trước với NCC về sản phẩm v&agrave; đơn h&agrave;ng</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>, Alilogi chỉ thanh to&aacute;n tiền theo y&ecirc;u cầu. Qu&yacute; kh&aacute;ch vui l&ograve;ng chủ động thực hiện khiếu nại với NCC. Alilogi kh&ocirc;ng chịu tr&aacute;ch nhiệm đền b&ugrave; đối với bất kỳ khoản đền b&ugrave; n&agrave;o li&ecirc;n quan đến mất m&aacute;t, tổn thất , kh&ocirc;ng giao h&agrave;ng, tr&igrave; ho&atilde;n hay giao thiếu h&agrave;ng từ b&ecirc;n b&aacute;n sản phẩm đến kho Trung Quốc.&nbsp;</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trường hợp h&agrave;ng h&oacute;a c&oacute; gi&aacute; trị cao bị lỗi hỏng do nh&agrave; cung cấp:</span></strong>
                                <ol style="list-style-type: circle;">
                                    <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>TH1: NCC &nbsp;kh&ocirc;ng chấp nhận bồi thường ho&agrave;n tiền m&agrave; y&ecirc;u cầu đổi trả, Alilogi sẽ hỗ trợ kh&acirc;u chuyển ngược nhưng Qu&yacute; kh&aacute;ch vui l&ograve;ng chịu mọi chi ph&iacute; li&ecirc;n quan.</span></li>
                                    <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>TH2: NCC kh&ocirc;ng chấp nhận bồi thường, Alilogi sẽ xem x&eacute;t v&agrave; đưa ra mức hỗ trợ ph&ugrave; hợp theo từng trường hợp cụ thể.</span></li>
                                </ol>
                            </li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với đơn h&agrave;ng PINDUODUO</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>, c&ocirc;ng ty chỉ đền b&ugrave; đối với trường hợp h&agrave;ng h&oacute;a bị thất lạc trong qu&aacute; tr&igrave;nh vận chuyển từ kho Trung Quốc về Việt Nam, kh&ocirc;ng hỗ trợ khiếu nại với shop v&agrave; kh&ocirc;ng c&oacute; tr&aacute;ch nhiệm đối với bất kỳ khoản đền b&ugrave; n&agrave;o li&ecirc;n quan đến mất m&aacute;t , tổn thất, kh&ocirc;ng giao h&agrave;ng, tr&igrave; ho&atilde;n hay giao thiếu h&agrave;ng h&oacute;a từ NCC.</span></li>
                        </ul>
                        <ul class="decimal_type" style="list-style-type: disc;margin-left:25.450000000000003px;">
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trường hợp c&ocirc;ng ty hỗ trợ qu&yacute; kh&aacute;ch đặt giao h&agrave;ng từ kho H&agrave; Nội th&ocirc;ng qua b&ecirc;n vận chuyển trung gian</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>, &nbsp;nếu xảy ra t&igrave;nh trạng mất h&agrave;ng y&ecirc;u cầu Qu&yacute; kh&aacute;ch cung cấp video quay lại qu&aacute; tr&igrave;nh b&oacute;c h&agrave;ng v&agrave; c&acirc;n lại kiện h&agrave;ng, Alilogi sẽ xử l&yacute; khiếu nại nếu sai s&oacute;t thuộc về ph&iacute;a c&ocirc;ng ty. Trong trường hợp Qu&yacute; kh&aacute;ch kh&ocirc;ng cung cấp đầy đủ video , Alilogi kh&ocirc;ng chịu tr&aacute;ch nhiệm xử l&yacute; v&agrave; đền b&ugrave; khiếu nại. Alilogi sẽ hỗ trợ khiếu nại nếu sai s&oacute;t thuộc về b&ecirc;n vận chuyển trung gian v&agrave; kh&ocirc;ng chịu tr&aacute;ch nhiệm đền b&ugrave; đối với trường hợp n&agrave;y.</span></li>
                            <li><strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Đối với h&agrave;ng h&oacute;a thực phẩm</span></strong><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>, khi nh&acirc;n vi&ecirc;n CSKH th&ocirc;ng b&aacute;o h&agrave;ng đ&atilde; về kho Việt Nam , Qu&yacute; kh&aacute;ch vui l&ograve;ng sắp xếp lấy h&agrave;ng trong ng&agrave;y. Alilogi kh&ocirc;ng hỗ trợ lưu kho nếu xảy ra t&igrave;nh trạng chuột ăn mất h&agrave;ng, Alilogi sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm đền b&ugrave;.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">5</span></strong><strong><span style="color:black;">.4. C&aacute;c lưu &yacute; cần thiết</span></strong></p>
                        <ul style="list-style-type: disc;margin-left:25.450000000000003px;">
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Alilogi thiết lập c&aacute;c mức ph&iacute; tr&ecirc;n cơ sở giảm thiếu tối đa chi ph&iacute; nhập h&agrave;ng đối với qu&yacute; kh&aacute;ch để tạo ra những lợi thế cạnh tranh. Với đặc th&ugrave; c&oacute; nhiều rủi ro kh&oacute; kiểm so&aacute;t trong hoạt động kiểm h&agrave;ng số lượng lớn v&agrave; vận chuyển đường bộ theo c&aacute;c bao h&agrave;ng như dễ m&oacute;p m&eacute;o hộp, ch&egrave;n &eacute;p sản phẩm&hellip; Ch&uacute;ng t&ocirc;i khuyến kh&iacute;ch qu&yacute; kh&aacute;ch lựa chọn h&agrave;ng h&oacute;a, c&aacute;ch thức đ&oacute;ng g&oacute;i vận chuyển ph&ugrave; hợp v&agrave; chia sẻ rủi ro với Alilogi khi xảy ra thiệt hại ngo&agrave;i mong muốn.&nbsp;</span></li>
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Việc đổi trả h&agrave;ng lu&ocirc;n chứa đựng nhiều rủi ro, Alilogi kh&ocirc;ng khuyến kh&iacute;ch xử l&yacute; khiếu nại dịch vụ theo phương &aacute;n đổi trả h&agrave;ng&nbsp;</span></li>
                            <li><span style='line-height:107%;font-family:"Times New Roman",serif;font-size:19px;'>Trong qu&aacute; tr&igrave;nh xử l&yacute; c&aacute;c khiếu nại dịch vụ c&oacute; li&ecirc;n quan đến NCC, Alilogi sẽ y&ecirc;u cầu sự hợp t&aacute;c từ Qu&yacute; kh&aacute;ch để việc thực hiện khiếu nại được giải quyết nhanh ch&oacute;ng v&agrave; ch&iacute;nh x&aacute;c.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">6</span></strong><strong><span style="color:black;">. TỪ CHỐI HOẶC NGỪNG CUNG CẤP DỊCH VỤ</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Trong c&aacute;c trường hợp sau</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">&nbsp;</span><span style="color:black;">c&oacute; quyền đơn phương từ chối cung cấp dịch vụ, bằng c&aacute;ch kh&oacute;a t&agrave;i khoản của Qu&yacute; kh&aacute;ch tr&ecirc;n hệ thống m&agrave; kh&ocirc;ng cần c&oacute; sự đồng &yacute; trước của Qu&yacute; kh&aacute;ch:</span></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Đặt h&agrave;ng với những th&ocirc;ng tin giả mạo, th&ocirc;ng tin li&ecirc;n hệ, địa chỉ, số điện thoại kh&ocirc;ng đ&uacute;ng.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">C&oacute; những y&ecirc;u cầu kh&ocirc;ng ch&iacute;nh đ&aacute;ng, vượt ra ngo&agrave;i phạm vi quản l&yacute; của&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;v&agrave; sai lệch về bản chất của dịch vụ Nhập h&agrave;ng hộ.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Đăng tải hoặc cung cấp th&ocirc;ng tin sai sự thật, với mục đ&iacute;ch l&agrave;m giảm uy t&iacute;n của&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;</span><span style="color:black;">cho b&ecirc;n thứ ba.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">C&oacute; h&agrave;nh vi gian lận khi nhận h&agrave;ng h&oacute;a.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Kh&aacute;ch h&agrave;ng ho&agrave;n to&agrave;n c&oacute; thể chủ động ngừng sử dụng dịch vụ của WeLog v&agrave; r&uacute;t nốt số tiền c&ograve;n lại ra khỏi v&iacute; hệ thống.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Trong trường hợp số dư trong t&agrave;i khoản v&iacute; tr&ecirc;n hệ thống của Qu&yacute; kh&aacute;ch vẫn c&ograve;n</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">&nbsp;</span><span style="color:black;">sẽ ho&agrave;n trả lại cho Qu&yacute; kh&aacute;ch trước khi chấm dứt dịch vụ.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">. CH&Iacute;NH S&Aacute;CH BẢO VỆ TH&Ocirc;NG TIN C&Aacute; NH&Acirc;N KH&Aacute;CH H&Agrave;NG</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">WeLog lu&ocirc;n t&ocirc;n trọng v&agrave; cam kết bảo mật những th&ocirc;ng tin c&aacute; nh&acirc;n mang t&iacute;nh ri&ecirc;ng tư của kh&aacute;ch h&agrave;ng.&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Để đ&aacute;p lại sự tin tưởng của kh&aacute;ch h&agrave;ng đ&atilde; cung cấp c&aacute;c th&ocirc;ng tin n&agrave;y khi truy cập v&agrave;o website&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">.vn, ch&uacute;ng t&ocirc;i đưa ra ch&iacute;nh s&aacute;ch cụ thể dưới đ&acirc;y để khẳng định vai tr&ograve; của ch&uacute;ng t&ocirc;i trong vấn đề bảo vệ quyền lợi của người truy cập.&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;chỉ thu thập c&aacute;c th&ocirc;ng tin phục vụ cho c&aacute;c hoạt động đặt h&agrave;ng với mục đ&iacute;ch cuối c&ugrave;ng l&agrave; đem đến những gi&aacute; trị tốt nhất cho qu&yacute; kh&aacute;ch.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.1. Mục đ&iacute;ch thu thập th&ocirc;ng tin c&aacute; nh&acirc;n kh&aacute;ch h&agrave;ng</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Kh&aacute;ch h&agrave;ng khi truy cập v&agrave;o website: https://</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">.vn/ v&agrave; tạo t&agrave;i khoản sẽ được y&ecirc;u cầu điền đầy đủ c&aacute;c th&ocirc;ng tin trong c&aacute;c trường theo mẫu c&oacute; sẵn như: Họ v&agrave; t&ecirc;n, số điện thoại (c&ocirc;ng ty hoặc c&aacute; nh&acirc;n), địa chỉ (văn ph&ograve;ng hoặc nh&agrave; ri&ecirc;ng), địa chỉ email (c&ocirc;ng ty hoặc c&aacute; nh&acirc;n),...&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Ch&uacute;ng t&ocirc;i c&oacute; thể thu thập số lần gh&eacute; thăm, c&aacute;c đường link Qu&yacute; kh&aacute;ch click v&agrave;o v&agrave; c&aacute;c th&ocirc;ng tin kh&aacute;c li&ecirc;n quan khi truy cập v&agrave;o website: https://</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">.vn/ bao gồm cả IP, tr&igrave;nh duyệt web, ng&ocirc;n ngữ sử dụng v&agrave; thời gian truy cập.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Mọi th&ocirc;ng tin được y&ecirc;u c&acirc;̀u đ&ecirc;̉ ho&agrave;n t&acirc;́t vi&ecirc;̣c đặt h&agrave;ng của Qu&yacute; kh&aacute;ch v&agrave; th&ocirc;ng b&aacute;o xử l&yacute; c&aacute;c vấn đề ph&aacute;t sinh (nếu c&oacute;). C&aacute;c khai b&aacute;o phải đảm bảo t&iacute;nh ch&iacute;nh x&aacute;c v&agrave; hợp ph&aacute;p.&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;kh&ocirc;ng chịu mọi tr&aacute;ch nhiệm li&ecirc;n quan đến ph&aacute;p luật của th&ocirc;ng tin khai b&aacute;o.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.2. Phạm vi sử dụng th&ocirc;ng tin c&aacute; nh&acirc;n</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Website: https://</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">.vn/ sử dụng c&aacute;c th&ocirc;ng tin Qu&yacute; kh&aacute;ch cung cấp để:&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Phục vụ quy tr&igrave;nh sử dụng dịch vụ tại&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;v&agrave; c&ocirc;ng t&aacute;c CSKH</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Ngăn ngừa c&aacute;c sai s&oacute;t nhầm lẫn c&aacute;c kh&aacute;ch h&agrave;ng, c&aacute;c hoạt động chiếm đoạt t&agrave;i khoản người d&ugrave;ng của kh&aacute;ch h&agrave;ng hoặc c&aacute;c hoạt động giả mạo.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Li&ecirc;n lạc v&agrave; giải quyết khiếu nại với kh&aacute;ch h&agrave;ng</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.3. Thời gian lưu trữ th&ocirc;ng tin c&aacute; nh&acirc;n</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Kh&ocirc;ng c&oacute; thời hạn ngoại trừ trường hợp kh&aacute;ch h&agrave;ng c&oacute; y&ecirc;u cầu hủy bỏ tới cho Ban quản trị hoặc C&ocirc;ng ty giải thể hoặc bị ph&aacute; sản. C&ograve;n lại trong mọi trường hợp th&ocirc;ng tin c&aacute; nh&acirc;n th&agrave;nh vi&ecirc;n sẽ được bảo mật tr&ecirc;n m&aacute;y chủ của https://</span><span style="color:black;">&nbsp;Alilogi</span><span style="color:black;">.vn/.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.4. Địa chỉ của đơn vị thu thập v&agrave; xử l&yacute; th&ocirc;ng tin c&aacute; nh&acirc;n</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Địa chỉ:&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Điện thoại:&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Email: &nbsp;</span><span style="color:black;">support@alilogi.vn</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.5. Phương tiện v&agrave; c&ocirc;ng cụ để người ti&ecirc;u d&ugrave;ng tiếp cận v&agrave; chỉnh sửa th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh&nbsp;</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Kh&aacute;ch h&agrave;ng c&oacute; quyền truy cập, kiểm tra, tự cập nhật v&agrave; chỉnh sửa th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh bằng c&aacute;ch đăng nhập v&agrave;o website&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">.vn hoặc y&ecirc;u cầu&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;thực hiện việc n&agrave;y.&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Kh&aacute;ch h&agrave;ng c&oacute; quyền gửi khiếu nại về việc lộ th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh cho b&ecirc;n thứ 3 đến&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">. Khi tiếp nhận phản hồi n&agrave;y, ch&uacute;ng t&ocirc;i sẽ x&aacute;c thực lại th&ocirc;ng tin v&agrave; c&oacute; tr&aacute;ch nhiệm trả lời l&yacute; do v&agrave; hướng dẫn kh&aacute;ch h&agrave;ng kh&ocirc;i phục v&agrave; bảo mật lại th&ocirc;ng tin.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- C&aacute;c h&igrave;nh thức khiếu nại:&nbsp;</span></p>
                        <ul style="margin-bottom:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Qua email:&nbsp;</span><span style="color:black;">support@alilogi.vn</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Qua điện thoại</span><span style="color:black;">:</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;text-indent:18.0pt;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.6. Những người hoặc tổ chức c&oacute; thể được tiếp cận với th&ocirc;ng tin c&aacute; nh&acirc;n của kh&aacute;ch h&agrave;ng</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Kh&aacute;ch h&agrave;ng đồng &yacute; rằng, trong trường hợp cần thiết, c&aacute;c tổ chức, c&aacute; nh&acirc;n sau c&oacute; thể tiếp cận với th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh bao gồm:</span></p>
                        <ul style="margin-bottom:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Ban quản trị&nbsp;</span><span style="color:black;">Alilogi</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">C&aacute;c đơn vị vận chuyển (T&ecirc;n, số điện thoại, địa chỉ nhận h&agrave;ng)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">B&ecirc;n thứ 3 c&oacute; dịch vụ t&iacute;ch hợp với website&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">.vn</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Cơ quan nh&agrave; nước c&oacute; thẩm quyền trong trường hợp c&oacute; y&ecirc;u cầu theo quy định tại quy chế hoạt động</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">Tất cả c&aacute;c th&ocirc;ng tin đều được sử dụng cho mục đ&iacute;ch ho&agrave;n th&agrave;nh đơn h&agrave;ng v&agrave; tăng chất lượng dịch vụ v&agrave; cam kết kh&ocirc;ng sử dụng cho bất kỳ mục đ&iacute;ch n&agrave;o kh&aacute;c.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><strong><span style="color:black;">7</span></strong><strong><span style="color:black;">.7. Cam kết bảo mật th&ocirc;ng tin c&aacute; nh&acirc;n của kh&aacute;ch h&agrave;ng</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Th&ocirc;ng tin c&aacute; nh&acirc;n của kh&aacute;ch h&agrave;ng đăng k&yacute; tr&ecirc;n website&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">.vn được ch&uacute;ng t&ocirc;i cam kết bảo mật tuyệt đối theo ch&iacute;nh s&aacute;ch bảo mật th&ocirc;ng tin c&aacute; nh&acirc;n được đăng tải tr&ecirc;n website ch&iacute;nh thức&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">.vn. Việc thu thập th&ocirc;ng tin của kh&aacute;ch h&agrave;ng chỉ được thực hiện khi c&oacute; sự đồng &yacute; của kh&aacute;ch h&agrave;ng trừ những trường hợp ph&aacute;p luật c&oacute; quy định kh&aacute;c về vấn đề n&agrave;y.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Kh&ocirc;ng sử dụng, kh&ocirc;ng chuyển giao, cung cấp hoặc tiết lộ cho b&ecirc;n thứ 3 về th&ocirc;ng tin kh&aacute;ch h&agrave;ng khi kh&ocirc;ng c&oacute; sự đồng &yacute; của kh&aacute;ch h&agrave;ng ngoại trừ c&aacute;c trường hợp được quy định tại quy định n&agrave;y hoặc quy định của ph&aacute;p luật.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:19px;font-family:"Times New Roman",serif;text-align:justify;background:white;'><span style="color:black;">- Trong trường hợp m&aacute;y chủ lưu trữ th&ocirc;ng tin bị hacker tấn c&ocirc;ng cướp quyền kiểm so&aacute;t dẫn đến mất th&ocirc;ng tin c&aacute; nh&acirc;n kh&aacute;ch h&agrave;ng.&nbsp;</span><span style="color:black;">Alilogi</span><span style="color:black;">&nbsp;sẽ c&oacute; tr&aacute;ch nhiệm th&ocirc;ng b&aacute;o v&agrave; l&agrave;m việc với c&aacute;c cơ quan chức năng để điều tra v&agrave; xử l&yacute; kịp thời, đồng thời th&ocirc;ng b&aacute;o cho kh&aacute;ch h&agrave;ng biết về vụ việc.&nbsp;</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;'><span style="line-height:107%;">&nbsp;&nbsp;</span></p>
                    </div>
                </div>
                <!-- Project One Row-->
                {{-- <div class="row gx-0 mb-5 mb-lg-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src="{{ asset('home/images/demo-image-01.jpg') }}" alt="..." /></div>
                    <div class="col-lg-6">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-left">
                                    <h4 class="text-white">Misty</h4>
                                    <p class="mb-0 text-white-50">An example of where you can put an image of a project, or anything else, along with a description.</p>
                                    <hr class="d-none d-lg-block mb-0 ms-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Project Two Row-->
                <div class="row gx-0 justify-content-center">
                    <div class="col-lg-6"><img class="img-fluid" src="{{ asset('home/images/demo-image-02.jpg') }}" alt="..." /></div>
                    <div class="col-lg-6 order-lg-first">
                        <div class="bg-black text-center h-100 project">
                            <div class="d-flex h-100">
                                <div class="project-text w-100 my-auto text-center text-lg-right">
                                    <h4 class="text-white">Mountains</h4>
                                    <p class="mb-0 text-white-50">Another example of a project with its respective description. These sections work well responsively as well, try this theme on a small screen!</p>
                                    <hr class="d-none d-lg-block mb-0 me-0" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> --}}
        </section>
        <!-- Signup-->
        {{-- <section class="signup-section" id="signup">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-5">Subscribe to receive updates!</h2>
                        <form class="form-signup d-flex flex-column flex-sm-row">
                            <input class="form-control flex-fill me-0 me-sm-2 mb-3 mb-sm-0" id="inputEmail" type="email" placeholder="Enter email address..." />
                            <button class="btn btn-primary" type="submit">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </section> --}}
        <!-- Contact-->
        <section class="contact-section bg-black">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Địa chỉ</h4>
                                <div class="small text-black-50">Số 521 Minh Khai, Quận Hai Bà Trưng, TP Hà Nội</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Email</h4>
                                <div class="small text-black-50"><a href="#!">support@alilogi.vn</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Hotline</h4>
                                <div class="small text-black-50">+84 971.226.601</div>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
                </div> --}}
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer bg-black small text-center text-white-50"><div class="container px-4 px-lg-5">Copyright &copy; Alilogi.vn 2021</div></footer>
        <!-- Bootstrap core JS-->
    </body>

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</html>
